### ISSUE TITLE
【依頼】最終課題挙動確認

### ISSUE THREAD

**Issue by atyoshimatsu** [atyoshimatsu/freemarket_sample_70_a_#1]
■URL
IPアドレス　http://54.199.47.20/
Github　https://github.com/atyoshimatsu/freemarket_sample_70_a_

■Basic認証
ID: freemarket_sample70a
Pass: 0601

■テスト用アカウント
○購入者用
メールアドレス: testuser2@gmail.com
パスワード: testuser

○購入用カード情報
番号：4242424242424242
期限：12/20
セキュリティコード：123

○出品者用
メールアドレス名: testuser3@gmail.com
パスワード: testuser

**Comment by iwataayumu** [comment]
atyoshimatsu 様

提出ありがとうございました！！
先程動作確認をさせていただきました
無事に必須機能全てLGTMとさせて頂きます！

遅くまで作業本当にお疲れさまでした！


コメント機能や、自己紹介メッセージ、閲覧回数など
綺麗で機能が豊富で動作確認していて楽しかったです！
